version: "2"
services:
  forward_service:
    image: forward_ros:11.7.1
    container_name: forward_ros
    network_mode: "host"
    tty: true
    stdin_open: true
    privileged: true
    # environment:
    #   - DISPLAY=$DISPLAY
    #   - QT_X11_NO_MITSHM=1
    #   - XAUTHORITY=/tmp/.docker.xauth
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - type: bind
        source: /home/infolab/docker_ws/bind_data
        target: /workspace/bind_data
      # - type: bind
      #   source: /tmp/.X11-unix
      #   target: /tmp/.X11-unix
      # - type: bind
      #   source: /tmp/.docker.xauth
      #   target: /tmp/.docker.xauth:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]